import { Analytics } from "@vercel/analytics/react";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Navbar from "./Components/Navbar";
import SliderNavbar from "./Components/SliderNavbar";

const inter = Inter({ subsets: ["latin"] });

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="font-serif ">
        <SessionProvider session={session}>

          <div className="pb-20">
          <Navbar/>

          </div>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
